export default {
  FONT_SIZE_SMALL: 10,
  FONT_SIZE_MEDIUM: 16,

  COLOR_PRIMARY: '#fab005',
  COLOR_RIPPLE: '#fcce62',

  ICON_SIZE_MEDIUM: 27,
  ICON_SIZE_SMALL: 20,

  IMAGE_HEIGHT_CARD: 180,
  IMAGE_HEIGHT_MODAL: 230,
}