export default {
  FONT_SIZE_SMALL: 10,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_MEDIUM_PLUS: 18,
  FONT_SIZE_LARGE_MINUS: 20,
  FONT_SIZE_LARGE: 22,
  FONT_SIZE_LARGE_PLUS: 24,
  FONT_SIZE_HUGE: 26,

  COLOR_BLACK: 'black',
  COLOR_WHITE: 'white',
  COLOR_PRIMARY: '#fab005',
  COLOR_RIPPLE: '#fcce62',
  COLOR_DISABLED: '#a8a8a8',

  ICON_SIZE_MEDIUM: 27,
  ICON_SIZE_SMALL: 20,

  IMAGE_HEIGHT_CARD: 180,
  IMAGE_HEIGHT_MODAL: 230,
}